# Generated by Django 6.0.6 on 2026-06-17 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Accessories', 'Accessories'), ('Bags', 'Bags'), ('Clothing', 'Clothing'), ('Stationery', 'Stationery'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Recovered', 'Recovered'), ('Given Away', 'Given Away'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('date_reported', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
