# Generated by Django 6.0.6 on 2026-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Library', 'Library'), ('Food Court', 'Food Court'), ('Hostel', 'Hostel'), ('Academic Block A', 'Academic Block A'), ('Academic Block B', 'Academic Block B'), ('Parking Area', 'Parking Area'), ('Bus Stop', 'Bus Stop'), ('Other', 'Other')], max_length=50),
        ),
    ]
