# Generated by Django 6.0.6 on 2026-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_reported',
            new_name='event_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Earphones', 'Earphones'), ('Charger', 'Charger'), ('Power Bank', 'Power Bank'), ('Wallet', 'Wallet'), ('Keys', 'Keys'), ('Watch', 'Watch'), ('Umbrella', 'Umbrella'), ('ID Card', 'ID Card'), ('Aadhaar Card', 'Aadhaar Card'), ('Driving License', 'Driving License'), ('Water Bottle', 'Water Bottle'), ('Bag', 'Bag'), ('Book', 'Book'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('Library', 'Library'), ('Food Court', 'Food Court'), ('Hostel', 'Hostel'), ('Academic Block A', 'Academic Block A'), ('Academic Block B', 'Academic Block B'), ('Parking Area', 'Parking Area'), ('Bus Stop', 'Bus Stop'), ('Other', 'Other')], max_length=100),
        ),
    ]
