# Generated by Django 6.0.6 on 2026-06-18 04:34

from django.db import migrations, models


def update_existing_categories(apps, schema_editor):
    Item = apps.get_model('core', 'Item')
    mapping = {
        'Watch': 'Watches',
        'Other': 'Miscellaneous Items',
        'Phone': 'Mobile Phones',
        'Laptop': 'Laptops',
        'Charger': 'Chargers',
        'Power Bank': 'Power Banks',
        'ID Card': 'Student ID Cards',
        'Aadhaar Card': 'Aadhaar Cards',
        'Driving License': 'Driving Licenses',
        'Water Bottle': 'Water Bottles',
        'Bag': 'Bags',
        'Book': 'Books',
    }
    for item in Item.objects.all():
        if item.category in mapping:
            item.category = mapping[item.category]
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_date_reported_item_event_date_and_more'),
    ]

    operations = [
        migrations.RunPython(update_existing_categories),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Mobile Phones', 'Mobile Phones'), ('Laptops', 'Laptops'), ('Earphones', 'Earphones'), ('Chargers', 'Chargers'), ('Power Banks', 'Power Banks'), ('Student ID Cards', 'Student ID Cards'), ('Aadhaar Cards', 'Aadhaar Cards'), ('Driving Licenses', 'Driving Licenses'), ('Other Documents', 'Other Documents'), ('Wallets', 'Wallets'), ('Keys', 'Keys'), ('Watches', 'Watches'), ('Umbrellas', 'Umbrellas'), ('Books', 'Books'), ('Stationery', 'Stationery'), ('Bags', 'Bags'), ('Water Bottles', 'Water Bottles'), ('Miscellaneous Items', 'Miscellaneous Items')], max_length=50),
        ),
    ]
